"""
Agent API Pydantic Schemas
==========================
Request and Response structures for the Multi-Agent system endpoints.
"""
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, field_validator


class AgentExecuteRequest(BaseModel):
    """POST /api/v1/agents/execute request payload."""

    query: str = Field(
        ...,
        min_length=3,
        max_length=3000,
        description="Software engineering request or codebase query",
        examples=["Perform a security review and check for bugs in the authentication middleware"],
    )
    repo_id: str = Field(
        ...,
        description="UUID of the indexed repository",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session ID for conversation tracking",
    )

    @field_validator("query")
    @classmethod
    def query_not_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("query must not be blank")
        return v.strip()


class AgentTraceStepSchema(BaseModel):
    agent: str
    action: str
    latency_ms: Optional[float] = None
    confidence: Optional[float] = None


class AgentOutputItemSchema(BaseModel):
    summary: str
    details: str
    data: Dict[str, Any] = Field(default_factory=dict)


class AgentExecuteResponse(BaseModel):
    """POST /api/v1/agents/execute response payload."""

    answer: str = Field(description="Consolidated final answer from the Multi-Agent system")
    plan: Dict[str, Any] = Field(description="Execution plan generated by the Planner agent")
    agent_outputs: Dict[str, AgentOutputItemSchema] = Field(
        description="Outputs produced by individual specialized engineering agents"
    )
    citations: List[Dict[str, Any]] = Field(description="Code attributions and source lines")
    confidence_score: float = Field(description="Groundedness and quality score assigned by Evaluation Agent")
    groundedness_ratio: float = Field(description="Ratio of grounded claims to total claims")
    execution_trace: List[Dict[str, Any]] = Field(description="Step-by-step agent execution trace")
    latency_ms: float = Field(description="Total end-to-end execution time in milliseconds")
    session_id: str
    repo_id: str
    error: Optional[str] = None
